// Generated by CoffeeScript 1.7.1
(function() {
  var exports,
    __hasProp = {}.hasOwnProperty;

  exports = this;

  document.addEventListener('DOMContentLoaded', function() {
    exports.inputView = {
      el: {
        searchText: document.getElementById('search-text'),
        perPage: document.getElementById('per-page'),
        maxReq: document.getElementById('max-req'),
        searchButton: document.getElementById('search-button'),
        canselButton: document.getElementById('cansel-button'),
        photosView: document.getElementById('photos-view')
      },
      getOptions: function() {
        var k, options;
        options = {
          text: this.el.searchText.value,
          per_page: this.el.perPage.value
        };
        for (k in options) {
          if (!__hasProp.call(options, k)) continue;
          if (options[k] === '') {
            delete options[k];
          }
        }
        return options;
      },
      getMaxConcurrentRequest: function() {
        var maxReq;
        maxReq = this.el.maxReq.value;
        return maxReq != null ? maxReq : false;
      },
      handleClick: function(e) {
        return this.fire('searchclick', e);
      },
      handleCansel: function(e) {
        console.log('canselclick');
        return this.fire('canselclick', e);
      }
    };
    makePublisher(inputView);
    inputView.el.searchButton.addEventListener('click', inputView.handleClick.bind(inputView));
    return inputView.el.canselButton.addEventListener('click', inputView.handleCansel.bind(inputView));
  });

}).call(this);
