// Generated by CoffeeScript 1.7.1
(function() {
  var exports;

  exports = this;

  document.addEventListener('DOMContentLoaded', function() {
    return exports.photosView = {
      el: {
        photosView: document.getElementById('photos-view')
      },
      appended: [],
      getAppended: function() {
        return this.appended;
      },
      appendPhotos: function(imgArr) {
        var frag, i, sent, v, _i, _len;
        if (imgArr == null) {
          return;
        }
        if (imgArr.length === 0) {
          return;
        }
        frag = document.createDocumentFragment();
        sent = imgArr.sent;
        for (i = _i = 0, _len = imgArr.length; _i < _len; i = ++_i) {
          v = imgArr[i];
          this.appended[sent[i]] = true;
          frag.appendChild(v);
        }
        return this.el.photosView.appendChild(frag);
      },
      clear: function() {
        var view;
        view = this.el.photosView;
        while (view.firstChild) {
          view.firstChild.onload = null;
          view.removeChild(view.firstChild);
        }
        return this.appended = [];
      }
    };
  });

}).call(this);
