// Generated by CoffeeScript 1.7.1
(function() {
  document.addEventListener('DOMContentLoaded', function() {
    var mediator;
    mediator = {
      appendNextPhoto: function() {
        var photos;
        photos = photosModel.getNextPhoto(photosView.getAppended());
        photos[0].className = 'flickr-img';
        return photosView.appendPhotos(photos);
      }
    };
    photosModel.on('delegateloading', 'preload', preloader);
    photosModel.on('loadedincreased', 'loadNext', photosModel);
    preloader.on('loaded', 'addPhoto', photosModel);
    photosModel.on('loadedincreased', 'appendNextPhoto', mediator);
    return photosModel.on('clear', 'clear', photosView);
  });

}).call(this);
