// Generated by CoffeeScript 1.7.1
(function() {
  var exports;

  exports = this;

  document.addEventListener('DOMContentLoaded', function() {
    var objfield;
    objfield = document.createElement('div');
    objfield.style.width = '0px';
    objfield.style.height = '0px';
    objfield.style.visibility = 'hidden';
    objfield.id = 'objfield';
    document.body.appendChild(objfield);
    exports.preloader = {
      preload: function(urlArr) {
        var body, fragment, i, obj, v, _i, _len;
        fragment = document.createDocumentFragment();
        body = document.body;
        for (i = _i = 0, _len = urlArr.length; _i < _len; i = ++_i) {
          v = urlArr[i];
          obj = document.createElement('object');
          obj.width = 0;
          obj.height = 0;
          obj.data = v;
          obj.onload = this.makeCreatePhoto(v);
          fragment.appendChild(obj);
        }
        return objfield.appendChild(fragment);
      },
      createPhoto: function() {},
      makeCreatePhoto: function(url) {
        return (function() {
          var img;
          img = document.createElement('img');
          img.src = url;
          return this.fire('loaded', img);
        }).bind(this);
      }
    };
    return makePublisher(preloader);
  });

}).call(this);
