// Generated by CoffeeScript 1.7.1
(function() {
  document.addEventListener('DOMContentLoaded', function() {
    return renderer.addUpdater(progressbarView.makeProgressbarUpdate());
  });

}).call(this);
