// Generated by CoffeeScript 1.7.1
(function() {
  var exports,
    __hasProp = {}.hasOwnProperty;

  exports = this;

  exports.stateful = {
    _state: {},
    changeState: function(statusObj) {
      return this._changeState(statusObj, false);
    },
    margeState: function(statusObj) {
      return this._changeState(statusObj, true);
    },
    getState: function(prop) {
      return this._state[prop];
    },
    _changeState: function(statusObj, marge) {
      var changed, margeProp, newStatus, ownPropChanged, state, status, type;
      state = this._state;
      changed = false;
      for (type in statusObj) {
        status = statusObj[type];
        ownPropChanged = state.hasOwnProperty(type) && state[type] !== status;
        margeProp = !state.hasOwnProperty(type) && marge;
        if (ownPropChanged || margeProp) {
          changed = true;
          state[type] = status;
          newStatus = {};
          newStatus[type] = status;
          this.fire("" + (type.toLowerCase()) + "change", newStatus);
        }
      }
      if (changed) {
        return this.fire("statechange", state);
      }
    }
  };

  exports.makeStateful = function(o) {
    var i, v;
    for (i in stateful) {
      if (!__hasProp.call(stateful, i)) continue;
      v = stateful[i];
      if (typeof v === 'function') {
        o[i] = v;
      }
    }
    return o._state = o._state || {};
  };

}).call(this);
