// Generated by CoffeeScript 1.7.1
(function() {
  document.addEventListener('DOMContentLoaded', function() {
    var mediator;
    mediator = {
      handleRendered: function() {
        return progressbarModel.changeState({
          canRenderRatio: false
        });
      },
      handleFull: function(statusObj) {
        if (statusObj.full) {
          return progressbarModel.fadeOut();
        }
      },
      handleHide: function() {
        progressbarModel.changeState({
          hidden: true
        });
        return progressbarModel.stop();
      }
    };
    progressbarModel.on('run', 'fadeIn', progressbarModel);
    progressbarView.on('ratiorendered', 'handleRendered', mediator);
    progressbarView.on('fullchange', 'handleFull', mediator);
    progressbarView.on('fadeend', 'fadeStop', progressbarModel);
    progressbarView.on('hide', 'handleHide', mediator);
    progressbarView.changeState({
      model: progressbarModel._state
    });
    progressbarModel.on('fadingchange', 'fadeInOut', progressbarView);
    return progressbarView.on('hide', 'initProgressbar', progressbarView);
  });

}).call(this);
